apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-stack-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-stack-app
  template:
    metadata:
      labels:
        app: mern-stack-app
    spec:
      containers:
        - name: mern-stack-app
          image: webmakaka/mern-stack-the-complite-guide
          env:
            - name: MONGO_URI
              value: 'mongodb://mongo-db-svc:27017/mongo-db'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
