apiVersion: skaffold/v2beta4
kind: Config
deploy:
  kubectl:
    manifests:
      - ../k8s/*
build:
  local:
    push: true
  artifacts:
    - image: webmakaka/mern-stack-the-complite-guide
      context: ../app
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
